export const getActivitiesTourSteps = (t) => [
  { element: '#activities-page-container', popover: { title: t('tour.activities.overview.title', 'Módulo de Actividades'), description: t('tour.activities.overview.description', 'Gestiona todas las tareas, seguimientos y acciones de tu equipo en un tablero Kanban dinámico.'), side: 'bottom', align: 'center' } },
  { element: '#activities-filters', popover: { title: t('tour.activities.filters.title', 'Filtros de Búsqueda'), description: t('tour.activities.filters.description', 'Busca actividades por texto o filtra rápidamente por nivel de prioridad.'), side: 'bottom', align: 'start' } },
  { element: '#activities-new-btn', popover: { title: t('tour.activities.newBtn.title', 'Nueva Actividad'), description: t('tour.activities.newBtn.description', 'Al hacer clic en "Siguiente", abriremos el formulario para crear una nueva actividad.'), side: 'bottom', align: 'end' } },
  { element: '#activities-kanban-board', popover: { title: t('tour.activities.kanban.title', 'Tablero Kanban'), description: t('tour.activities.kanban.description', 'Organiza tus actividades arrastrando las tarjetas entre las diferentes columnas de estado.'), side: 'top', align: 'start' } },
  { element: '[data-tour-activity-card="true"]', popover: { title: t('tour.activities.card.title', 'Tarjeta de Actividad'), description: t('tour.activities.card.description', 'Cada tarjeta muestra la información clave. Al hacer clic en "Siguiente", veremos sus detalles completos.'), side: 'top', align: 'start' } },
//   { element: '#activities-action-view', popover: { title: t('tour.activities.actionView.title', 'Ver Detalles'), description: t('tour.activities.actionView.description', 'Al hacer clic en "Siguiente", abriremos el panel lateral con toda la información, subtareas y comentarios.'), side: 'left', align: 'start' } },
  { element: '#activities-finish', popover: { title: t('tour.activities.finish.title', '¡Tour Completado!'), description: t('tour.activities.finish.description', 'Ahora puedes gestionar las actividades de tu equipo de manera eficiente.'), side: 'top', align: 'center' } }
]
export const activitiesTourConfig = { id: 'activities-main-tour', autoStart: false }